# Generated by Django 5.0.7 on 2024-07-20 02:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_user_characters'),
    ]

    operations = [
        migrations.AddField(
            model_name='characters',
            name='archetype',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='characters',
            name='healthPoints',
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name='characters',
            name='image',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='characters',
            name='relationships',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='characters',
            name='reputation',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
