# Generated by Django 5.0.7 on 2024-07-20 19:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_characters_archetype_characters_healthpoints_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='characters',
            name='characterClass',
            field=models.CharField(max_length=150),
        ),
        migrations.AlterField(
            model_name='characters',
            name='name',
            field=models.CharField(max_length=150),
        ),
        migrations.AlterField(
            model_name='characters',
            name='nickname',
            field=models.CharField(max_length=150),
        ),
        migrations.AlterField(
            model_name='party',
            name='partyRules',
            field=models.TextField(),
        ),
    ]
