# Generated by Django 5.1 on 2024-08-28 01:01

import django.db.models.deletion
import django.utils.timezone
import model_utils.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_alter_characters_characterclass_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Desires',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('is_removed', models.BooleanField(default=False)),
                ('type', models.CharField(max_length=200)),
                ('description', models.TextField()),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.RemoveField(
            model_name='dm',
            name='userId',
        ),
        migrations.AddField(
            model_name='user',
            name='dmId',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='api.dm'),
        ),
        migrations.AlterField(
            model_name='party',
            name='partySystem',
            field=models.CharField(choices=[('D&D5th', 'D&D5th'), ('GoodSociety', 'Good Society')], max_length=150),
        ),
    ]
