# Generated by Django 5.1 on 2024-08-28 19:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_relations'),
    ]

    operations = [
        migrations.AddField(
            model_name='characters',
            name='desires',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='api.desires'),
        ),
        migrations.AlterField(
            model_name='characters',
            name='relationships',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='api.relations'),
        ),
    ]
