# Generated by Django 5.1 on 2024-08-28 20:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0010_archetypes_characters_economic_status_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='characters',
            name='archetype',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='api.archetypes'),
        ),
    ]
