# Generated by Django 5.1 on 2024-08-28 20:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0011_alter_characters_archetype'),
    ]

    operations = [
        migrations.AddField(
            model_name='characters',
            name='tokens',
            field=models.IntegerField(default=3),
        ),
    ]
