# Generated by Django 5.1 on 2024-09-01 02:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0015_alter_userprofile_nickname'),
    ]

    operations = [
        migrations.AddField(
            model_name='party',
            name='chars_playing',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='api.characters'),
        ),
        migrations.AddField(
            model_name='party',
            name='published',
            field=models.BooleanField(default=False),
        ),
    ]
