# Generated by Django 5.1 on 2024-09-01 21:38

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0016_party_chars_playing_party_published'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='characters',
            name='creator',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='character_creator', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='characters',
            name='player',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='character_player', to=settings.AUTH_USER_MODEL),
        ),
    ]
